# Generated by Django 5.0.1 on 2024-01-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="singer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="playlists.singer",
            ),
        ),
    ]
