# Generated by Django 5.0.1 on 2024-01-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_music_singer"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="musics",
            field=models.ManyToManyField(
                related_name="playlists", to="playlists.music"
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="playlists.singer",
            ),
        ),
    ]
